cors:
    filter:
        enable: true
db:
    config: profiles/local/db.properties

logging:
    config: classpath:profiles/logback-spring.xml
server:
    tomcat:
        basedir: /tmp

javamelody:
    enabled: true
    name: javamelodyFilter
    init-parameters:
        log: true


